### ISSUE TITLE
No information about license

### ISSUE THREAD

**Issue by yarwelp** [parasyte/alt64#3]
This repository does not seem to include a license.

**Comment by parasyte** [comment]
Yeah. Unfortunately, this project hasn't ever included any license information. The repository was created as a means to organize a project that was originally written and maintained without any kind of open source _best practices_.

The original author is "saturnu" on the Krikzz forum (see the link on the repo front page). That would be the best place to ask which license this software should be released under.

As a secondary issue, some of the included code was written by Krikzz himself for the official menu software, and may have different licensing requirements.
